// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtXMms6KcNij0LSi_WZoNjoV4hXl3ROHw',
    appId: '1:1077502269810:web:4b575e6631d055013ca5eb',
    messagingSenderId: '1077502269810',
    projectId: 'islam-qu',
    authDomain: 'islam-qu.firebaseapp.com',
    storageBucket: 'islam-qu.appspot.com',
    measurementId: 'G-9N080J6N8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMcpqEARoO4lguaYHgKrKZ1rHNn_2cK-Y',
    appId: '1:1077502269810:android:35da612c1320f7d43ca5eb',
    messagingSenderId: '1077502269810',
    projectId: 'islam-qu',
    storageBucket: 'islam-qu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMdDykdQ9uNgZY2gENa3n7BqbFVyxOkPU',
    appId: '1:1077502269810:ios:26017a3fce01d7713ca5eb',
    messagingSenderId: '1077502269810',
    projectId: 'islam-qu',
    storageBucket: 'islam-qu.appspot.com',
    iosBundleId: 'islam.qu.islamqu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMdDykdQ9uNgZY2gENa3n7BqbFVyxOkPU',
    appId: '1:1077502269810:ios:26017a3fce01d7713ca5eb',
    messagingSenderId: '1077502269810',
    projectId: 'islam-qu',
    storageBucket: 'islam-qu.appspot.com',
    iosBundleId: 'islam.qu.islamqu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtXMms6KcNij0LSi_WZoNjoV4hXl3ROHw',
    appId: '1:1077502269810:web:fa9035c4007279f63ca5eb',
    messagingSenderId: '1077502269810',
    projectId: 'islam-qu',
    authDomain: 'islam-qu.firebaseapp.com',
    storageBucket: 'islam-qu.appspot.com',
    measurementId: 'G-6J43PWEKJC',
  );

}